kind = "web"
previewPath = "/"
title = "Labkafe Reseller"
version = "1.0.0"
id = "artifacts/labkafe-reseller"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19974

[services.development]
run = "pnpm --filter @workspace/labkafe-reseller run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/labkafe-reseller", "run", "build" ]
publicDir = "artifacts/labkafe-reseller/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19974"
BASE_PATH = "/"
